main.yml: Import and update tester step

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -103,6 +103,33 @@ jobs:
         git config --global user.name "${{ github.actor }}"
         git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
 
+      # Test Your Personal 'Local Manifests' against The ROM
+    - name: Test Local Manifests
+      run: |
+             if [ "${{ github.event.inputs.BUILD_DIFFERENT_ROM }}" == "echo 'Build Starting!'" ]; then
+              case "${{ github.event.inputs.BASE_PROJECT }}" in
+                  "ArrowOS 13.1")
+                    repo init -u https://github.com/ArrowOS/android_manifest.git -b arrow-13.1 --depth=1
+                  ;;
+                  "DerpFest 13.0")
+                    repo init -u https://github.com/DerpFest-AOSP/manifest.git -b 13 --depth=1
+                  ;;
+                  "LineageOS 21.0")
+                    repo init -u https://github.com/crdroidandroid/android.git -b 14.0 --git-lfs --depth=1
+                  ;;
+                  "LineageOS 20.0")
+                    repo init -u https://github.com/LineageOS/android.git -b lineage-20.0 --git-lfs --depth=1
+                  ;;
+              esac
+             else
+                      ${{ github.event.inputs.BUILD_DIFFERENT_ROM }}
+                      
+              fi
+              git clone ${{ github.event.inputs.LOCAL_MANIFEST }} --depth 1 -b ${{ github.event.inputs.LOCAL_MANIFEST_BRANCH }} .repo/local_manifests && \
+              timeout 1m repo sync --force-sync || { exit_code=$?; [ $exit_code -eq 124 ] || (echo "Error: Process failed with exit code $exit_code"; exit $exit_code); }
+              rm -rf .repo
+      timeout-minutes: 10  
+      
       # Download and configure 'crave'.
     - name: Configure the 'crave' environment
       run: |
