main.yml: Properly indent.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -105,45 +105,44 @@ jobs:
       # Test Your Personal 'Local Manifests' against The ROM
     - name: Test Local Manifests
       run: |
-             if [ -z ${{ github.event.inputs.BUILD_DIFFERENT_ROM }} ]; then
-              case "${{ github.event.inputs.BASE_PROJECT }}" in
-                  "ArrowOS 13.1")
-                    repo init -u https://github.com/ArrowOS/android_manifest.git -b arrow-13.1 --depth=1
-                  ;;
-                  "DerpFest 13.0")
-                    repo init -u https://github.com/DerpFest-AOSP/manifest.git -b 13 --depth=1
-                  ;;
-                  "LineageOS 21.0")
-                    repo init -u https://github.com/LineageOS/android.git -b lineage-21.0 --git-lfs --depth=1
-                  ;;
-                  "LineageOS 20.0")
-                    repo init -u https://github.com/LineageOS/android.git -b lineage-20.0 --git-lfs --depth=1
-                  ;;
-              esac
-            else
-              ${{ github.event.inputs.BUILD_DIFFERENT_ROM }}
-            fi
+        if [ -z ${{ github.event.inputs.BUILD_DIFFERENT_ROM }} ]; then
+          case "${{ github.event.inputs.BASE_PROJECT }}" in
+              "ArrowOS 13.1")
+                repo init -u https://github.com/ArrowOS/android_manifest.git -b arrow-13.1 --depth=1
+              ;;
+              "DerpFest 13.0")
+                repo init -u https://github.com/DerpFest-AOSP/manifest.git -b 13 --depth=1
+              ;;
+              "LineageOS 21.0")
+                repo init -u https://github.com/LineageOS/android.git -b lineage-21.0 --git-lfs --depth=1
+              ;;
+              "LineageOS 20.0")
+                repo init -u https://github.com/LineageOS/android.git -b lineage-20.0 --git-lfs --depth=1
+              ;;
+          esac
+        else
+          ${{ github.event.inputs.BUILD_DIFFERENT_ROM }}
+        fi
 
-              git clone ${{ github.event.inputs.LOCAL_MANIFEST }} --depth 1 -b ${{ github.event.inputs.LOCAL_MANIFEST_BRANCH }} .repo/local_manifests
-
-              timeout 1m repo sync --force-sync
-              if [ $? == 124 ]; then
-                echo "Error: Process failed with exit code $exit_code"
-                exit 0
-              fi
+        git clone ${{ github.event.inputs.LOCAL_MANIFEST }} --depth 1 -b ${{ github.event.inputs.LOCAL_MANIFEST_BRANCH }} .repo/local_manifests
+        timeout 1m repo sync --force-sync
+        if [ $? == 124 ]; then
+          echo "Error: Process failed with exit code $exit_code"
+          exit 0
+        fi
       timeout-minutes: 10  
       
       # Download and configure 'crave'.
     - name: Configure the 'crave' environment
       run: |
         if [ "${DCDEVSPACE}" == "1" ]; then
-        echo 'No need to set up crave, we are already running in devspace!'
+          echo 'No need to set up crave, we are already running in devspace!'
         else
           curl -s https://raw.githubusercontent.com/accupara/crave/master/get_crave.sh | bash -s --
           mv ${PWD}/crave ${HOME}/bin/
           sudo ln -sf /home/${USER}/bin/crave /usr/bin/crave
           envsubst < ${PWD}/crave.conf.sample >> ${PWD}/crave.conf
-          rm -rf ${PWD}/crave.conf.sample          
+          rm -rf ${PWD}/crave.conf.sample
         fi
       env:
         CRAVE_USERNAME: ${{  secrets.CRAVE_USERNAME  }}
@@ -183,10 +182,10 @@ jobs:
         if [ ! $? == 0 ]; then \
           curl -o .repo/local_manifests ${{ github.event.inputs.LOCAL_MANIFEST }}; \
         fi \
-        
+
         # Sync the repositories
         repo sync -c -j\$(nproc --all) --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync  && \
-        
+
         # Set up build environment
         export BUILD_USERNAME=${{ github.actor }} ; \
         export BUILD_HOSTNAME=crave ; \
