Use previous return value instead

diff --git a/.github/workflows/selfhosted.yml b/.github/workflows/selfhosted.yml
--- a/.github/workflows/selfhosted.yml
+++ b/.github/workflows/selfhosted.yml
@@ -377,14 +377,16 @@ jobs:
 
     - name: Check for a broken .bashrc
       run: |
-        output=$( { source ~/.bashrc; } 2>&1 ) || {
-          echo "$output"
+        output=$( { source ~/.bashrc; } 2>&1 )
+        status=$?
+        echo "$output"
+        if [[ $status -ne 0 ]]; then
           echo "You have a broken .bashrc, please contact a Crave.io Administrator"
           exit 1
-        }
-        echo "$output" | grep -q "cannot execute" && (echo "You have a broken .bashrc, please contact a Crave.io Administrator"; exit 1) # check again, to be doubly sure
+        fi
+        echo "$output" | grep -q "cannot execute" && (echo "You have a broken .bashrc, please contact a Crave.io Administrator"; exit 1)
 
-      # Create a project folder
+        # Create a project folder
     - name: Create Project Folders
       run: |
         echo "DCDEVSPACE status: ${DCDEVSPACE}"
