Fail if .bashrc is broken Handles a strange edgecase where if the bashrc was broken, DCDEVSPACE would be set to 1 but doesn't work as such in if statements
Example:
if [[ "$DCDEVSPACE" == "1" ]]; then   echo "DCDEVSPACE contains 1"; fi

Working environment:
DCDEVSPACE contains 1

Broken .bashrc:
(no output)

Actual Error: .bashrc: cannot execute binary file

A workaround is to match it with wildcards on both sides

Drop set -e
Allow the command to fail so we have some output

Use previous return value instead

Try to set +x before taking output

Debug: See what breaks

Switch && to own if

Give output to users with working bashrc too

Don't be verbose, debugging done

Cleanup set +x

diff --git a/.github/workflows/selfhosted.yml b/.github/workflows/selfhosted.yml
--- a/.github/workflows/selfhosted.yml
+++ b/.github/workflows/selfhosted.yml
@@ -375,11 +375,33 @@ jobs:
     - name: Cleanup
       run: rm -rf * # This cleans github actions workspace
 
-      # Create a project folder
+    - name: Check for a broken .bashrc
+      continue-on-error: true
+      run: |
+        (
+          set +e
+          output=$(source ~/.bashrc 2>&1)
+          status=$?
+          echo "$output"
+          if [[ $status -ne 0 ]]; then
+            echo "You have a broken .bashrc, please contact a Crave.io Administrator"
+            exit 1
+          else
+            echo ".bashrc looks okay, no explicit errors"
+          fi
+
+          # Double check to be sure
+          if echo "$output" | grep -q "cannot execute"; then
+            echo "You have a broken .bashrc, please contact a Crave.io Administrator"
+            exit 1
+          fi
+        )
+
+        # Create a project folder
     - name: Create Project Folders
       run: |
         echo "DCDEVSPACE status: ${DCDEVSPACE}"
-        if [[ "${DCDEVSPACE}" != "1" ]]; then
+        if [[ $DCDEVSPACE != *1* ]]; then
 
           #curl -s https://raw.githubusercontent.com/accupara/crave/master/get_crave.sh | bash -s -- 
 
