selfhosted.yml: Bring if else to destroy step

diff --git a/.github/workflows/selfhosted.yml b/.github/workflows/selfhosted.yml
--- a/.github/workflows/selfhosted.yml
+++ b/.github/workflows/selfhosted.yml
@@ -408,4 +408,9 @@ jobs:
 
       # Remove 'crave' clone
     - name: Destroy Crave Clone
-      run: crave clone destroy -y $PROJECTFOLDER || echo "Error removing $PROJECTFOLDER"
+      run: |
+        if grep -q "$PROJECTFOLDER" <(crave clone list --json | jq -r '.clones[]."Cloned At"') && [ "${DCDEVSPACE}" == "1" ]; then
+          crave clone destroy -y $PROJECTFOLDER || echo "Error removing $PROJECTFOLDER"
+        else          
+          rm -rf $PROJECTFOLDER || true
+        fi
