main.yml: Stop asking for full build command.

diff --git a/.github/workflows/selfhosted.yml b/.github/workflows/selfhosted.yml
--- a/.github/workflows/selfhosted.yml
+++ b/.github/workflows/selfhosted.yml
@@ -5,7 +5,7 @@
 # SPDX-License-Identifier: Apache-2.0
 #
 
-name: Start job for building through Crave(self-hosted)
+name: Start job for building through Crave.
 on:
   workflow_dispatch:
     # Various inputs to simplify usage of workflow.
@@ -23,7 +23,6 @@ on:
       BUILD_DIFFERENT_ROM:
         description: "Command to initialize a different 'repo' project:"
         required: false
-        default: "echo 'Build Starting!'"
       REMOVALS:
         description: "Folders to be removed before syncing:"
         required: false
@@ -44,9 +43,14 @@ on:
         required: true
         default: "lineage_oxygen"
       BUILD_COMMAND:
-        description: 'Command to be used for compiling:'
+        description: 'Type of build to execute:'
         required: true
-        default: 'mka bacon'
+        default: 'ROM'
+        type: choice
+        options:
+          - 'ROM'
+          - 'Recovery'
+          - 'Vendor image'
       BUILD_TYPE:
         description: 'Type of build:'
         required: true
@@ -66,50 +70,10 @@ on:
         - 'no'
 
 jobs:
-  run-devspace-and-tmux:
-    runs-on: ubuntu-latest
-
-    steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
-
-    - name: Set up environment
-      run: |
-        sudo apt-get update
-        sudo apt-get install -y tmux
-
-      # Download and configure 'crave'.
-    - name: Configure the 'crave' environment
-      run: |
-        if [ "${DCDEVSPACE}" == "1" ]; then
-        echo 'No need to set up crave, we are already running in devspace!'
-        else
-          mkdir ${HOME}/bin/
-          curl -s https://raw.githubusercontent.com/accupara/crave/master/get_crave.sh | bash -s --
-          mv ${PWD}/crave ${HOME}/bin/
-          sudo ln -sf /home/${USER}/bin/crave /usr/bin/crave
-          envsubst < ${PWD}/crave.conf.sample >> ${PWD}/crave.conf
-          rm -rf ${PWD}/crave.conf.sample          
-        fi
-      env:
-        CRAVE_USERNAME: ${{  secrets.CRAVE_USERNAME  }}
-        CRAVE_TOKEN: ${{  secrets.CRAVE_TOKEN  }}
-
-    - name: Run crave devspace
-      run: |
-        crave devspace -- "if tmux has-session -t ghactions; then 
-          echo "Runner is already Running" 
-        else 
-          tmux kill-session -t ghactions;
-          tmux new-session -d -s ghactions 
-          tmux send-keys -t ghactions './actions-runner/run.sh' Enter 
-          echo "Runner Started"
-        fi "
   test:
-    timeout-minutes: 720      
     name: Build using foss.crave.io
-    needs: run-devspace-and-tmux    
-    runs-on: self-hosted
+      # Change this to self-hosted after setting up devspace as github actions runner
+    runs-on: ubuntu-latest
     concurrency:
       group: ${{ github.workflow }}-${{ github.ref }}
     steps:
@@ -142,45 +106,52 @@ jobs:
       run: |
         git config --global user.name "${{ github.actor }}"
         git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
-
+        if [ -z ${GITHUB_TOKEN} ]; then
+          echo machine github.com login ${GITHUB_TOKEN} password ${GITHUB_TOKEN} >> ${PWD}/.netrc
+        fi
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       # Test Your Personal 'Local Manifests' against The ROM
     - name: Test Local Manifests
       run: |
-             if [ "${{ github.event.inputs.BUILD_DIFFERENT_ROM }}" == "echo 'Build Starting!'" ]; then
-              case "${{ github.event.inputs.BASE_PROJECT }}" in
-                  "ArrowOS 13.1")
-                    repo init -u https://github.com/ArrowOS/android_manifest.git -b arrow-13.1 --depth=1
-                  ;;
-                  "DerpFest 13.0")
-                    repo init -u https://github.com/DerpFest-AOSP/manifest.git -b 13 --depth=1
-                  ;;
-                  "LineageOS 21.0")
-                    repo init -u https://github.com/LineageOS/android.git -b lineage-21.0 --git-lfs --depth=1
-                  ;;
-                  "LineageOS 20.0")
-                    repo init -u https://github.com/LineageOS/android.git -b lineage-20.0 --git-lfs --depth=1
-                  ;;
-              esac
-             else
-                      ${{ github.event.inputs.BUILD_DIFFERENT_ROM }}
-                      
-              fi
-              git clone ${{ github.event.inputs.LOCAL_MANIFEST }} --depth 1 -b ${{ github.event.inputs.LOCAL_MANIFEST_BRANCH }} .repo/local_manifests && \
-              timeout 1m repo sync --force-sync || { exit_code=$?; [ $exit_code -eq 124 ] || (echo "Error: Process failed with exit code $exit_code"; exit $exit_code); }
-              rm -rf .repo
+        if [ -z ${{ github.event.inputs.BUILD_DIFFERENT_ROM }} ]; then
+          case "${{ github.event.inputs.BASE_PROJECT }}" in
+              "ArrowOS 13.1")
+                repo init -u https://github.com/ArrowOS/android_manifest.git -b arrow-13.1 --depth=1
+              ;;
+              "DerpFest 13.0")
+                repo init -u https://github.com/DerpFest-AOSP/manifest.git -b 13 --depth=1
+              ;;
+              "LineageOS 21.0")
+                repo init -u https://github.com/LineageOS/android.git -b lineage-21.0 --git-lfs --depth=1
+              ;;
+              "LineageOS 20.0")
+                repo init -u https://github.com/LineageOS/android.git -b lineage-20.0 --git-lfs --depth=1
+              ;;
+          esac
+        else
+          ${{ github.event.inputs.BUILD_DIFFERENT_ROM }}
+        fi
+
+        git clone ${{ github.event.inputs.LOCAL_MANIFEST }} --depth 1 -b ${{ github.event.inputs.LOCAL_MANIFEST_BRANCH }} .repo/local_manifests
+        timeout 1m repo sync --force-sync
+        if [ $? == 124 ]; then
+          echo "Error: Process failed with exit code $exit_code"
+          exit 0
+        fi
       timeout-minutes: 10  
       
       # Download and configure 'crave'.
     - name: Configure the 'crave' environment
       run: |
         if [ "${DCDEVSPACE}" == "1" ]; then
-        echo 'No need to set up crave, we are already running in devspace!'
+          echo 'No need to set up crave, we are already running in devspace!'
         else
           curl -s https://raw.githubusercontent.com/accupara/crave/master/get_crave.sh | bash -s --
           mv ${PWD}/crave ${HOME}/bin/
           sudo ln -sf /home/${USER}/bin/crave /usr/bin/crave
           envsubst < ${PWD}/crave.conf.sample >> ${PWD}/crave.conf
-          rm -rf ${PWD}/crave.conf.sample          
+          rm -rf ${PWD}/crave.conf.sample
         fi
       env:
         CRAVE_USERNAME: ${{  secrets.CRAVE_USERNAME  }}
@@ -189,21 +160,21 @@ jobs:
       # Initialize the previously choosen 'repo' project.
     - name: Set the 'crave' project
       run: |
-        jq '.projects = []' ~/crave.conf > tmp && mv tmp ~/crave.conf
         case "${{ github.event.inputs.BASE_PROJECT }}" in
           "ArrowOS 13.1")
-            repo init -u https://github.com/ArrowOS/android_manifest.git -b arrow-13.1 --depth=1
+            crave set --projectID 73
           ;;
           "DerpFest 13.0")
-            repo init -u https://github.com/DerpFest-AOSP/manifest.git -b 13 --depth=1
+            crave set --projectID 64
           ;;
           "LineageOS 21.0")
-            repo init -u https://github.com/LineageOS/android.git -b lineage-21.0 --git-lfs --depth=1
+            crave set --projectID 72
           ;;
           "LineageOS 20.0")
-            repo init -u https://github.com/accupara/los20.git -b lineage-20.0 --git-lfs --depth=1
+            crave set --projectID 36
           ;;
         esac
+      id: pwd
         
       # Create a 'crave' job for building.
     - name: Start compilation through 'crave'
@@ -212,6 +183,7 @@ jobs:
            export CLEAN="clean"
         fi
 
+        crave push ${PWD}/.netrc -d ${HOME}/.netrc
         crave run --no-patch --${CLEAN} "rm -rf .repo/local_manifests/ ${{ github.event.inputs.REMOVALS }} && \
         # Clone local_manifests repository
         ${{ github.event.inputs.BUILD_DIFFERENT_ROM }} ; \
@@ -220,21 +192,35 @@ jobs:
         if [ ! $? == 0 ]; then \
           curl -o .repo/local_manifests ${{ github.event.inputs.LOCAL_MANIFEST }}; \
         fi \
-        
+
         # Sync the repositories
-        repo sync -c -j\$(nproc --all) --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync  && \
-        
+        repo sync -c -j $(nproc) --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync  && \
+
         # Set up build environment
-        export BUILD_USERNAME=${{ github.actor }} ; \
+        export BUILD_USERNAME=${{ github.actor }}; \
         export BUILD_HOSTNAME=crave ; \
         source build/envsetup.sh && \
 
         # Build the ROM
         lunch ${{ github.event.inputs.PRODUCT_NAME }}-${{ github.event.inputs.BUILD_TYPE }} && \
+        case "${{ github.event.inputs.BUILD_COMMAND }}" in
+            "ROM")
+              mka
+            ;;
+            "Recovery")
+              mm -j && m ramdisk-nodeps && m recoveryimage-nodeps
+            ;;
+            "Boot image")
+              mka bootimage
+            ;;
+            "Vendor image")
+              mka vendorimage
+            ;;
+        esac
+
         make installclean && \
         ${{ github.event.inputs.BUILD_COMMAND }}"
-      timeout-minutes: 720  
-      
+
       # Only reach this wheter the user killed the workflow.
     - name: Execute if the job is cancelled
       if: ${{ cancelled() }}
@@ -261,13 +247,5 @@ jobs:
         tag_name: ${{ github.run_id }}
         body: |
           Target: ${{ github.event.inputs.PRODUCT_NAME }}-${{ github.event.inputs.BUILD_TYPE }}
-      continue-on-error: true
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-      # Upload to Telegram
-    - name: Upload Using telegram-upload
-      run: |
-        telegram-upload ${{ github.event.inputs.DEVICE_NAME }}/recovery.img ${{ github.event.inputs.DEVICE_NAME }}/boot.img ${{ github.event.inputs.DEVICE_NAME }}/vendor_boot.img ${{ github.event.inputs.DEVICE_NAME }}/vendor.img ${{ github.event.inputs.DEVICE_NAME }}/system.img ${{ github.event.inputs.DEVICE_NAME }}/*.zip
-      continue-on-error: true
-      
