Fail if .bashrc is broken Handles a strange edgecase where if the bashrc was broken, DCDEVSPACE would be set to 1 but doesn't work as such in if statements
Example:
if [[ "$DCDEVSPACE" == "1" ]]; then   echo "DCDEVSPACE contains 1"; fi

Working environment:
DCDEVSPACE contains 1

Broken .bashrc:
(no output)

Actual Error: .bashrc: cannot execute binary file

A workaround is to match it with wildcards on both sides

diff --git a/.github/workflows/selfhosted.yml b/.github/workflows/selfhosted.yml
--- a/.github/workflows/selfhosted.yml
+++ b/.github/workflows/selfhosted.yml
@@ -375,11 +375,21 @@ jobs:
     - name: Cleanup
       run: rm -rf * # This cleans github actions workspace
 
+    - name: Check for a broken .bashrc
+      run: |
+        set -e
+        output=$( { source ~/.bashrc; } 2>&1 ) || {
+          echo "$output"
+          echo "You have a broken .bashrc, please contact a Crave.io Administrator"
+          exit 1
+        }
+        echo "$output" | grep -q "cannot execute" && (echo "You have a broken .bashrc, please contact a Crave.io Administrator"; exit 1) # check again, to be doubly sure
+
       # Create a project folder
     - name: Create Project Folders
       run: |
         echo "DCDEVSPACE status: ${DCDEVSPACE}"
-        if [[ "${DCDEVSPACE}" != "1" ]]; then
+        if [[ $DCDEVSPACE != *1* ]]; then
 
           #curl -s https://raw.githubusercontent.com/accupara/crave/master/get_crave.sh | bash -s -- 
 
