Make twrp up to date

diff --git a/.github/workflows/twrp-legacy.yml b/.github/workflows/twrp-legacy.yml
--- a/.github/workflows/twrp-legacy.yml
+++ b/.github/workflows/twrp-legacy.yml
@@ -5,7 +5,7 @@
 # SPDX-License-Identifier: Apache-2.0
 #
 
-name: TWRP Builder(Legacy)
+name: Crave Builder
 on:
   workflow_dispatch:
     # Various inputs to simplify usage of workflow.
@@ -13,7 +13,7 @@ on:
       BASE_PROJECT:
         description: 'Choose a base project:'
         required: true
-        default: 'LineageOS 20.0'
+        default: 'TWRP 12.1'
         type: choice
         options:
           - 'TWRP 12.1'
@@ -31,7 +31,7 @@ on:
       LOCAL_MANIFEST_BRANCH:
         description: "Personal local manifest's branch:"
         required: false
-        default: 'twrp-oxygen'
+        default: 'lineage-oxygen'
       DEVICE_NAME:
         description: "Device's codename:"
         required: true
@@ -39,15 +39,15 @@ on:
       PRODUCT_NAME:
         description: "Product to build:"
         required: true
-        default: "twrp_oxygen"
+        default: "lineage_oxygen"
       BUILD_COMMAND:
         description: 'Command to be used for compiling:'
         required: true
-        default: 'mka recoveryimage'
+        default: 'make recoveryimage'
       BUILD_TYPE:
         description: 'Type of build:'
         required: true
-        default: 'eng'
+        default: 'userdebug'
         type: choice
         options: 
         - 'eng'
@@ -63,23 +63,141 @@ on:
         - 'no'
 
 jobs:
+  prepare:
+    name: Prepare for Building
+    runs-on: ubuntu-latest
+    steps:
+    - name: Set Project variables
+      id: proj-variables
+      run: |
+        case "${{ github.event.inputs.BASE_PROJECT }}" in
+        "TWRP 12.1")
+          export PROJECTFOLDER="/crave-devspaces/TWRP12"
+          export PROJECTID="78"
+          export REPO_INIT="repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1 --depth=1"
+        ;;
+        esac
+        echo "Building on ${{ github.event.inputs.BASE_PROJECT }} project"
+        echo "PROJECTFOLDER=$PROJECTFOLDER" >> "$GITHUB_OUTPUT"
+        echo "PROJECTID=$PROJECTID"  >> "$GITHUB_OUTPUT"
+        echo "REPO_INIT=$REPO_INIT" >> "$GITHUB_OUTPUT"
+    outputs:
+      PROJECTFOLDER: ${{ steps.proj-variables.outputs.PROJECTFOLDER }}
+      PROJECTID: ${{ steps.proj-variables.outputs.PROJECTID }}
+      REPO_INIT: ${{ steps.proj-variables.outputs.REPO_INIT }}
+
   test:
-    name: Build TWRP using foss.crave.io
+    name: Test Local Manifests
+    needs: prepare
+    runs-on: ubuntu-latest
+    steps:
+      # Accept Project Variables
+    - name: Set Repo Project
+      run: |
+        PROJECTFOLDER="${{ needs.prepare.outputs.PROJECTFOLDER }}"
+        PROJECTID="${{ needs.prepare.outputs.PROJECTID }}"
+        REPO_INIT="${{ needs.prepare.outputs.REPO_INIT }}"
+
+        echo "PROJECTFOLDER=$PROJECTFOLDER" >> "$GITHUB_ENV"
+        echo "PROJECTID=$PROJECTID"  >> "$GITHUB_ENV"
+        echo "REPO_INIT=$REPO_INIT" >> "$GITHUB_ENV"
+
+      # Download and configure 'repo'.
+    - name: Configure the 'repo' environment
+      run: |
+        # Check if repo is already installed
+        if ! command -v repo >/dev/null 2>&1; then
+          echo "Repo not found. Installing now..."
+          # Create bin directory if it doesn't exist
+          mkdir -p ~/bin
+          # Download repo script
+          curl https://storage.googleapis.com/git-repo-downloads/repo >> ~/bin/repo
+          # Make repo script executable
+          chmod a+x ~/bin/repo
+          # Create symbolic link to /usr/bin/repo
+          sudo ln -sf "/home/$(whoami)/bin/repo" "/usr/bin/repo"
+          echo "Repo installation complete."
+        else
+          echo "Repo already installed."
+        fi
+      continue-on-error: true
+      
+      # Generate 'git' credential in base of the workflow's author.
+    - name: Set-up 'git' credential(s)
+      run: |
+        git config --global user.name "${{ github.actor }}"
+        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
+
+      # Test Your Personal 'Local Manifests' against The ROM
+    - name: Test Local Manifests
+      if: ${{ github.event.inputs.BUILD_DIFFERENT_ROM != 'skip' }}
+      run: |
+        rm -rf tester
+        mkdir tester
+        cd tester 
+        if [ "${{ github.event.inputs.BUILD_DIFFERENT_ROM }}" == "echo 'Build Starting!'" ]; then
+          $REPO_INIT
+        else
+          ${{ github.event.inputs.BUILD_DIFFERENT_ROM }}
+        fi 
+        git clone ${{ github.event.inputs.LOCAL_MANIFEST }} --depth 1 -b ${{ github.event.inputs.LOCAL_MANIFEST_BRANCH }} .repo/local_manifests && \
+
+        if [ ! $? == 0 ]; then \
+          curl -o .repo/local_manifests ${{ github.event.inputs.LOCAL_MANIFEST }}; \
+          echo "Git clone failed, downloading through curl instead..."; \ 
+        fi \
+    
+        timeout 1m repo sync --force-sync || { exit_code=$?; [ $exit_code -eq 124 ] || (echo "Error: Process failed with exit code $exit_code"; exit $exit_code); }
+        du -csh . # Output Size when done
+        rm -rf .repo
+      timeout-minutes: 10
+    outputs:
+      PROJECTFOLDER: ${{ needs.prepare.outputs.PROJECTFOLDER }}
+      PROJECTID: ${{ needs.prepare.outputs.PROJECTID }}
+      REPO_INIT: ${{ needs.prepare.outputs.REPO_INIT }}
+
+  build:
+    name: Build using foss.crave.io
+      # Change this to self-hosted after setting up devspace as github actions runner
     runs-on: ubuntu-latest
     concurrency:
       group: ${{ github.workflow }}-${{ github.ref }}
     steps:
+      # Accept Project Variables
+    - name: Set Repo Project
+      run: |
+        PROJECTFOLDER="${{ needs.test.outputs.PROJECTFOLDER }}"
+        PROJECTID="${{ needs.test.outputs.PROJECTID }}"
+        REPO_INIT="${{ needs.test.outputs.REPO_INIT }}"
+
+        echo "PROJECTFOLDER=$PROJECTFOLDER" >> "$GITHUB_ENV"
+        echo "PROJECTID=$PROJECTID"  >> "$GITHUB_ENV"
+        echo "REPO_INIT=$REPO_INIT" >> "$GITHUB_ENV"
+
       # Create a project folder
     - name: Create Project Folders
       run: |
-        mkdir -p devspace
-        sudo mkdir -p /crave-devspaces
-        sudo ln -sf ${pwd}/devspace /crave-devspaces
-        sudo chmod 777 /crave-devspaces
-        export PROJECTFOLDER="/crave-devspaces/TWRP"
-        mkdir -p $PROJECTFOLDER
-        echo "PROJECTFOLDER=$PROJECTFOLDER" >> "$GITHUB_ENV"
-        echo "OLDDIR=$(pwd)" >> "$GITHUB_ENV"
+
+        if [ "${DCDEVSPACE}" != "1" ]; then
+          echo "Symlinking devspace folder"
+          mkdir -p devspace
+          sudo mkdir -p /crave-devspaces
+          sudo ln -sf ${pwd}/devspace /crave-devspaces
+          sudo chmod 777 /crave-devspaces
+        else
+          echo "We are already running in devspace... Skipping Symlinks"
+        fi
+        if grep -q "$PROJECTFOLDER" <(crave clone list --json | jq -r '.clones[]."Cloned At"') && [ "${DCDEVSPACE}" == "1" ]; then
+          crave clone destroy -y $PROJECTFOLDER || echo "Error removing $PROJECTFOLDER"
+        else          
+        rm -rf $PROJECTFOLDER || true
+        fi
+
+        if [ "${DCDEVSPACE}" == "1" ]; then
+          crave clone create --projectID $PROJECTID $PROJECTFOLDER || echo "Crave clone create failed!"
+        else
+          mkdir $PROJECTFOLDER
+        fi
 
       # Check-out in order to access the repository's files.
     - name: Check-out to repository
@@ -95,10 +213,21 @@ jobs:
       # Download and configure 'repo'.
     - name: Configure the 'repo' environment
       run: |
-        mkdir "${HOME}/bin"
-        curl https://storage.googleapis.com/git-repo-downloads/repo >> "${HOME}/bin/repo"
-        chmod a+x "${HOME}/bin/repo"
-        sudo ln -sf "/home/${USER}/bin/repo" "/usr/bin/repo"
+        # Check if repo is already installed
+        if ! command -v repo >/dev/null 2>&1; then
+          echo "Repo not found. Installing now..."
+          # Create bin directory if it doesn't exist
+          mkdir -p ~/bin
+          # Download repo script
+          curl https://storage.googleapis.com/git-repo-downloads/repo >> ~/bin/repo
+          # Make repo script executable
+          chmod a+x ~/bin/repo
+          # Create symbolic link to /usr/bin/repo
+          sudo ln -sf "/home/$(whoami)/bin/repo" "/usr/bin/repo"
+          echo "Repo installation complete."
+        else
+          echo "Repo already installed."
+        fi
       continue-on-error: true
       
       # Generate 'git' credential in base of the workflow's author.
@@ -106,59 +235,33 @@ jobs:
       run: |
         git config --global user.name "${{ github.actor }}"
         git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
-      
-      # Test Your Personal 'Local Manifests' against The ROM
-    - name: Test Local Manifests
-      run: |
-            cd $PROJECTFOLDER
-            rm -rf tester
-            mkdir tester
-            cd tester 
-            if [ "${{ github.event.inputs.BUILD_DIFFERENT_ROM }}" == "echo 'Build Starting!'" ]; then
-              case "${{ github.event.inputs.BASE_PROJECT }}" in
-                  "TWRP 12.1")
-                    repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1 --depth=1
-                  ;;
-              esac
-             else
-                      ${{ github.event.inputs.BUILD_DIFFERENT_ROM }}
-                      
-              fi
-              git clone ${{ github.event.inputs.LOCAL_MANIFEST }} --depth 1 -b ${{ github.event.inputs.LOCAL_MANIFEST_BRANCH }} .repo/local_manifests && \
-              timeout 1m repo sync --force-sync || { exit_code=$?; [ $exit_code -eq 124 ] || (echo "Error: Process failed with exit code $exit_code"; exit $exit_code); }
-              rm -rf .repo
-      timeout-minutes: 10
 
-      # Initialize the previously choosen 'repo' project.
-    - name: Set the 'crave' project
-      run: |
-        cd $PROJECTFOLDER
-        case "${{ github.event.inputs.BASE_PROJECT }}" in
-          "TWRP 12.1")
-            repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
-        esac
-        if [ "${{ github.event.inputs.BUILD_DIFFERENT_ROM }}" == "echo 'Build Starting!'" ]; then
-          echo "Building ${{ github.event.inputs.BASE_PROJECT }}"
-        else
-          export BUILD_DIFFERENT_ROM="${{ github.event.inputs.BUILD_DIFFERENT_ROM }}"
-        fi
-        echo "BUILD_DIFFERENT_ROM=$BUILD_DIFFERENT_ROM" >> "$GITHUB_ENV"
+      # Send Build 'start' notification
+    - name: Telegram Notification
+      continue-on-error: true
+      uses: xinthink/action-telegram@v1.1
+      with:
+        chatId: ${{ secrets.TELEGRAM_TO }}
+        botToken: ${{ secrets.TELEGRAM_TOKEN }}
+        jobStatus: "Build Started"
+        skipSuccess: false
 
       # Download and configure 'crave'.
     - name: Configure the 'crave' environment
       run: |
+        mkdir -p $PROJECTFOLDER/.repo/manifests
         if [ "${DCDEVSPACE}" == "1" ]; then
-        echo 'No need to set up crave, we are already running in devspace!'
+          echo 'No need to set up crave, we are already running in devspace!'
         else
           curl -s https://raw.githubusercontent.com/accupara/crave/master/get_crave.sh | bash -s --
           mv ${PWD}/crave ${HOME}/bin/
           sudo ln -sf /home/${USER}/bin/crave /usr/bin/crave
           envsubst < ${PWD}/crave.conf.sample >> ${PWD}/crave.conf
-          rm -rf ${PWD}/crave.conf.sample  
-          cp crave.conf $PROJECTFOLDER        
+          rm -rf ${PWD}/crave.conf.sample
+          cp crave.conf $PROJECTFOLDER
         fi
         if [[ -z "${{ secrets.CUSTOM_YAML }}" ]]; then
-          cp yamls/crave.yaml.twrp $PROJECTFOLDER/.repo/manifests
+          cp yamls/crave.yaml.twrp.legacy $PROJECTFOLDER/.repo/manifests/crave.yaml
           echo "No Custom Configuration Found, Using Template!"
         else
           touch $PROJECTFOLDER/.repo/manifests/crave.yaml || true
@@ -168,11 +271,29 @@ jobs:
       env:
         CRAVE_USERNAME: ${{  secrets.CRAVE_USERNAME  }}
         CRAVE_TOKEN: ${{  secrets.CRAVE_TOKEN  }}
-        
-      # Create a 'crave' job for building.
-    - name: Start compilation through 'crave'
+
+      # Initialize the previously choosen 'repo' project.
+    - name: Set the 'crave' project
       run: |
         cd $PROJECTFOLDER
+        echo "Running $REPO_INIT"
+        $REPO_INIT
+
+        if [ "${{ github.event.inputs.BUILD_DIFFERENT_ROM }}" == "echo 'Build Starting!'" ]; then
+          export BUILD_DIFFERENT_ROM="$REPO_INIT"
+          echo "Building $BUILD_DIFFERENT_ROM"
+        else
+          export BUILD_DIFFERENT_ROM="${{ github.event.inputs.BUILD_DIFFERENT_ROM }}"
+          echo "Building $BUILD_DIFFERENT_ROM"
+        fi
+        echo "BUILD_DIFFERENT_ROM=$BUILD_DIFFERENT_ROM" >> "$GITHUB_ENV"
+
+      # Create a 'crave' job for building.
+    - name: Start compilation through 'crave'
+      if: ${{ github.event.inputs.BUILD_DIFFERENT_ROM != 'skip' }}
+      run: |
+        cd $PROJECTFOLDER
+
         if [ "${{ github.event.inputs.CLEAN_BUILD }}" == "yes" ]; then
            export CLEAN="clean"
         fi
@@ -180,26 +301,39 @@ jobs:
         crave run --no-patch --${CLEAN} "rm -rf .repo/local_manifests/ ${{ github.event.inputs.REMOVALS }} && \
         # Clone local_manifests repository
         $BUILD_DIFFERENT_ROM ; \
-
         git clone ${{ github.event.inputs.LOCAL_MANIFEST }} --depth 1 -b ${{ github.event.inputs.LOCAL_MANIFEST_BRANCH }} .repo/local_manifests && \
 
         if [ ! $? == 0 ]; then \
           curl -o .repo/local_manifests ${{ github.event.inputs.LOCAL_MANIFEST }}; \
+          echo "Git clone failed, downloading through curl instead..."; \
         fi \
-        
+
         # Sync the repositories
         /opt/crave/resync.sh  && \
-        
+
         # Set up build environment
         export BUILD_USERNAME=${{ github.actor }} ; \
         export BUILD_HOSTNAME=crave ; \
         source build/envsetup.sh && \
-        export ALLOW_MISSING_DEPENDENCIES=true; \
+
+        echo "Repository: ${{ github.repository }}"; \
+        echo "Run ID: ${{ github.run_id }}"; \
 
         # Build the ROM
         lunch ${{ github.event.inputs.PRODUCT_NAME }}-${{ github.event.inputs.BUILD_TYPE }} && \
         make installclean && \
         ${{ github.event.inputs.BUILD_COMMAND }}"
+
+      # Send Build 'status' notification
+    - name: Telegram Notification
+      if:  ${{ success()  || cancelled() || failure() }}
+      continue-on-error: true
+      uses: xinthink/action-telegram@v1.1
+      with:
+        chatId: ${{ secrets.TELEGRAM_TO }}
+        botToken: ${{ secrets.TELEGRAM_TOKEN }}
+        jobStatus: ${{ job.status }}
+        skipSuccess: false
 
       # Only reach this wheter the user killed the workflow.
     - name: Execute if the job is cancelled
@@ -214,4 +348,16 @@ jobs:
         cd $PROJECTFOLDER
         echo "${{ secrets.GITHUB_TOKEN }}" > token.txt
         crave push token.txt -d $(crave ssh -- pwd | grep -v Select | sed -s 's/\r//g')/
-        crave ssh -- "bash /opt/crave/github-actions/upload.sh '${{ github.run_id }}' '${{ github.event.inputs.DEVICE_NAME }}'  '${{ github.repository }}' '${{ github.event.inputs.PRODUCT_NAME }}-${{ github.run_id }}'"
+        crave ssh -- "bash /opt/crave/github-actions/upload.sh '${{ github.run_id }}' '${{ github.event.inputs.DEVICE_NAME }}'  '${{ github.repository }}' '${{ github.event.inputs.PRODUCT_NAME }}-${{ github.run_id }}' '${{ secrets.EXTRA_FILES }}'"
+
+      # Pull Errors and Display them
+    - name: Display error.log
+      if: ${{ failure() }}
+      id: errorlog
+      run: |
+        cd $PROJECTFOLDER
+        crave ssh -- sleep 1
+        crave pull out/error.log
+        echo "Displaying out/error.log"
+        cat out/error.log
+        #if [[ -z "${{ secrets.CUSTOM_YAML }}" ]]; then
