Cleanup: Drop '&&' and '\' everywhere

diff --git a/.github/workflows/twrp.yml b/.github/workflows/twrp.yml
--- a/.github/workflows/twrp.yml
+++ b/.github/workflows/twrp.yml
@@ -140,13 +140,13 @@ jobs:
         else
           ${{ github.event.inputs.BUILD_DIFFERENT_ROM }}
         fi 
-        git clone ${{ github.event.inputs.LOCAL_MANIFEST }} --depth 1 -b ${{ github.event.inputs.LOCAL_MANIFEST_BRANCH }} .repo/local_manifests && \
+        git clone ${{ github.event.inputs.LOCAL_MANIFEST }} --depth 1 -b ${{ github.event.inputs.LOCAL_MANIFEST_BRANCH }} .repo/local_manifests ;
 
-        if [ ! $? == 0 ]; then \
-          curl -o .repo/local_manifests ${{ github.event.inputs.LOCAL_MANIFEST }}; \
-          echo "Git clone failed, downloading through curl instead..."; \ 
-        fi \
-    
+        if [ ! $? == 0 ]; then 
+          curl -o .repo/local_manifests ${{ github.event.inputs.LOCAL_MANIFEST }};
+          echo "Git clone failed, downloading through curl instead..."; 
+        fi 
+
         timeout 1m repo sync --force-sync || { exit_code=$?; [ $exit_code -eq 124 ] || (echo "Error: Process failed with exit code $exit_code"; exit $exit_code); }
         du -csh . # Output Size when done
         rm -rf .repo
@@ -299,30 +299,30 @@ jobs:
            export CLEAN="clean"
         fi
 
-        crave run --no-patch --${CLEAN} "rm -rf .repo/local_manifests/ ${{ github.event.inputs.REMOVALS }} && \
+        crave run --no-patch --${CLEAN} "rm -rf .repo/local_manifests/ ${{ github.event.inputs.REMOVALS }} ;
         # Clone local_manifests repository
-        $BUILD_DIFFERENT_ROM ; \
-        git clone ${{ github.event.inputs.LOCAL_MANIFEST }} --depth 1 -b ${{ github.event.inputs.LOCAL_MANIFEST_BRANCH }} .repo/local_manifests && \
+        $BUILD_DIFFERENT_ROM ;
+        git clone ${{ github.event.inputs.LOCAL_MANIFEST }} --depth 1 -b ${{ github.event.inputs.LOCAL_MANIFEST_BRANCH }} .repo/local_manifests ;
 
-        if [ ! $? == 0 ]; then \
-          curl -o .repo/local_manifests ${{ github.event.inputs.LOCAL_MANIFEST }}; \
-          echo "Git clone failed, downloading through curl instead..."; \
-        fi \
+        if [ ! $? == 0 ]; then 
+          curl -o .repo/local_manifests ${{ github.event.inputs.LOCAL_MANIFEST }};
+          echo "Git clone failed, downloading through curl instead...";
+        fi 
 
         # Sync the repositories
-        /opt/crave/resync.sh  && \
+        /opt/crave/resync.sh  ;
 
         # Set up build environment
-        export BUILD_USERNAME=${{ github.actor }} ; \
-        export BUILD_HOSTNAME=crave ; \
-        source build/envsetup.sh && \
+        export BUILD_USERNAME=${{ github.actor }} ;
+        export BUILD_HOSTNAME=crave ;
+        source build/envsetup.sh ;
 
-        echo "Repository: ${{ github.repository }}"; \
-        echo "Run ID: ${{ github.run_id }}"; \
+        echo "Repository: ${{ github.repository }}";
+        echo "Run ID: ${{ github.run_id }}";
 
         # Build the ROM
-        lunch ${{ github.event.inputs.PRODUCT_NAME }}-${{ github.event.inputs.BUILD_TYPE }} && \
-        make installclean && \
+        lunch ${{ github.event.inputs.PRODUCT_NAME }}-${{ github.event.inputs.BUILD_TYPE }} ;
+        make installclean ;
         ${{ github.event.inputs.BUILD_COMMAND }}"
 
       # Send Build 'status' notification
